[package]
name = "sudoku-rs"
version = "0.1.0"
authors = ["Andre Sharpe <andre.sharpe@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
clap = "2.33.1"
